{
 "title": "默认指标监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(gfast_process_cpu_seconds_total,app)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(gfast_process_cpu_seconds_total,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "流量分布", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GRPC Input 占比(app 维度)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(peer)(increase(gfast_request_server_handle_total{type=\"grpc\",host=~\"$host\",app=~\"$app\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GRPC Input 占比(host维度)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(peer_host)(increase(gfast_request_server_handle_total{type=\"grpc\",host=~\"$host\",app=~\"$app\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GRPC Output 占比(app 维度)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(server)(increase(client_handle_total{type=\"grpc\",host=~\"$host\",app=~\"$app\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(gfast_process_cpu_seconds_total{app=~\"$app\",host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{app}}-{{host}}"
    }
   ]
  },
  {
   "title": "内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gfast_process_resident_memory_bytes{app=~\"$app\",host=~\"$host\"}",
     "legendFormat": "{{app}}-{{host}}"
    }
   ]
  },
  {
   "title": "协程数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{app=~\"$app\",host=~\"$host\"}",
     "legendFormat": "{{app}}-{{host}}"
    }
   ]
  },
  {
   "title": "线程数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_threads{app=~\"$app\",host=~\"$host\"}",
     "legendFormat": "{{app}}-{{host}}"
    }
   ]
  },
  {
   "title": "gc 调度延迟",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{app=~\"$app\",host=~\"$host\",quantile=\"0.75\"}",
     "legendFormat": "{{app}}-{{host}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "go 协程调度延迟",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum by(le,app,host)(rate(go_sched_latencies_seconds_bucket{app=~\"$app\",host=~\"$host\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "黄金指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "HTTP QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum by(method)(rate(gfast_request_server_handle_total{app=~\"$app\",host=~\"$host\",type=\"http\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GRPC QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum by(method)(rate(gfast_request_server_handle_total{app=~\"$app\",host=~\"$host\",type=\"grpc\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 接口 P99 延迟",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum by(method,le) (rate(gfast_request_server_handle_seconds_bucket{app=~\"$app\",host=~\"$host\",type=\"http\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GRPC 接口 P99 延迟",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum by(method,le) (rate(gfast_request_server_handle_seconds_bucket{app=~\"$app\",host=~\"$host\",type=\"grpc\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 错误率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum by(status,method)(rate(gfast_request_server_handle_seconds_count{status!=\"200\",type=\"http\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GRPC 错误率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum by(status,method)(rate(gfast_request_server_handle_seconds_count{status!=\"0\",type=\"grpc\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}